[nimib]
srcDir = "docsrc"
homeDir = "docs"

[nimibook]
language = "en-us"
title = "NimiSlides"
description = "NimiSlides Documentation"
git_repository_url = "https://github.com/HugoGranstrom/nimiSlides"