name: Generate nimiSlides docs

on:
  push:
    branches:
      - main

jobs:
  gen:
    name: Generate and deploy docs
    runs-on: ubuntu-latest  

    steps:
      - uses: actions/checkout@v2
      - name: apt install
        run: sudo apt install -y libpcre3 libblas-dev liblapack-dev
      - uses: iffy/install-nim@v5
      - name: Generate
        run: |
          set -e
          nimble sync -y
          nimble docs
          nimble buildDocs
          nimble buildBook
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
