name: Generate nimiSlides docs

on:
  pull_request:
    branches:
      - main

jobs:
  gen:
    name: Validate PR
    runs-on: ubuntu-latest  

    steps:
      - uses: actions/checkout@v2
      - uses: iffy/install-nim@v4
      - name: Install deps
        run: |
          nimble install -y
          nimble docsDeps
      - name: Build compiler-docs
        run: nimble docs
      - name: Build slideshows
        run:  nimble buildDocs
      - name: Build book
        run:  nimble buildBook
