name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim:
          - 'stable'
          - 'devel'
      fail-fast: false
    name: Nim ${{ matrix.nim }}
    steps:
      - uses: actions/checkout@v2
      - uses: jiro4989/setup-nim-action@v2.2.2
        with:
          nim-version: ${{ matrix.nim }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: sudo apt install libpcre3 libpcre3-dev liblapack-dev
      - run: nimble install nimble -g
      - name: Install deps
        run: |
          set -e
          nimble install -y https://github.com/zetashift/fontim https://github.com/HugoGranstrom/cdt -g
          nimble sync -y
          nimble setup
      - name: Build compiler-docs
        run: nimble docs
      - name: Build slideshows
        run:  nimble buildDocs
      - name: Build book
        run:  nimble buildBook
