name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim:
          - '1.6.x'
          - 'stable'
          - 'devel'
      fail-fast: false
    name: Nim ${{ matrix.nim }}
    steps:
      - uses: actions/checkout@v2
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install deps
        run: |
          nimble install -y
          nimble docsDeps
      - name: Build compiler-docs
        run: nimble docs
      - name: Build slideshows
        run:  nimble buildDocs
      - name: Build book
        run:  nimble buildBook
