name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim:
          - 'binary:1.6.x'
          - 'binary:stable'
          - 'devel'
      fail-fast: false
    name: Nim ${{ matrix.nim }}
    steps:
      - uses: actions/checkout@v2
      - uses: iffy/install-nim@v4
        with:
          version: ${{ matrix.nim }}
      - name: Install deps
        run: |
          nimble install -y
          nimble docsDeps
      - name: Build compiler-docs
        run: nimble docs
      - name: Build slideshows
        run:  nimble buildDocs
      - name: Build book
        run:  nimble buildBook
